---
title: Madhav Paudel
timezone: UTC+05:45
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tagline: IT Enthusiast
email: info@poudelmadhav.com.np
description: 'I am student of Computer Science and Information Technology at Tribhuvan
  University.'
baseurl: 
url: blog.poudelmadhav.com.np
logourl: "/assets/images/logo.png"
author: Madhav Paudel
author_thumbnail: "/assets/images/avatar.jpg"
    
theme:
highlight_color: "#205081"
social:
github: poudelmadhav
twitter: poudelmadhav143
facebook: poudelmadhav143
gplus: +madhavpoudel143
pinterest: poudelmadhav143
show_share_buttons: true
show_author_info: true
disqus_shortname: madhav-jekyll-blog
google_analytics_key: 
google_webmaster_key: 
markdown: kramdown
permalink: pretty
gems:
- jekyll-paginate
paginate: 5
paginate_path: page:num
exclude:
- CNAME
- Gemfile
- Rakefile
- README.md
- ".gitignore"
- ".sass-cache"
- Gemfile.lock
sass:
  sass_dir: assets/css/_sass
  style: compressed
